# Generated by Django 3.2 on 2021-04-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='socket',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='socket',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
