# Generated by Django 3.2 on 2021-04-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0005_auto_20210428_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='benchmark_mark',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='benchmark_mark',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ram',
            name='the_volume_of_one_memory_module',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
