# Generated by Django 3.2 on 2021-04-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0006_auto_20210428_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ram',
            name='number_of_modules_included',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
