# Generated by Django 3.2 on 2021-04-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0007_alter_ram_number_of_modules_included'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ram',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
