# Generated by Django 3.2 on 2021-04-27 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0008_alter_ram_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ram',
            old_name='rank',
            new_name='degree',
        ),
    ]
