# Generated by Django 3.2 on 2021-04-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0009_rename_rank_ram_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hard25',
            name='hdd_capacity',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hard35',
            name='hdd_capacity',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
