# Generated by Django 3.2 on 2021-04-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0011_alter_ssd_drive_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssd_m2',
            name='drive_volume',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
