# Generated by Django 3.2 on 2021-04-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0013_alter_powersupply_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooler',
            name='link',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='link',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='link',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hard25',
            name='link',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hard35',
            name='link',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='link',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ram',
            name='link',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='link',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ssd_m2',
            name='link',
            field=models.URLField(null=True, unique=True),
        ),
    ]
