# Generated by Django 3.2 on 2021-05-02 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0015_auto_20210502_0506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hard35',
            old_name='eatures_optional',
            new_name='features_optional',
        ),
        migrations.AddField(
            model_name='hard25',
            name='features_optional',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
