# Generated by Django 3.2 on 2021-05-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0017_alter_motherboard_number_and_type_of_usb_on_the_rear_panel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='model',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
