# Generated by Django 3.2 on 2021-05-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0018_alter_motherboard_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='internal_usb_connectors_on_board',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
