# Generated by Django 3.2 on 2021-05-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0019_alter_motherboard_internal_usb_connectors_on_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='m_2_storage_logical_interface',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
