# Generated by Django 3.2 on 2021-05-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0020_alter_motherboard_m_2_storage_logical_interface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='modes_of_operation_of_several_pci_e_x16_slots',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
