# Generated by Django 3.2 on 2021-05-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0021_alter_motherboard_modes_of_operation_of_several_pci_e_x16_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='features_optional',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
