# Generated by Django 3.2 on 2021-05-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0023_alter_gpu_features_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpu',
            name='benchmark_mark',
        ),
        migrations.AddField(
            model_name='cpu',
            name='thread_mark',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='g2s_mark',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='g3d_mark',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='benchmark_mark',
            field=models.FloatField(default=-1, null=True),
        ),
    ]
