# Generated by Django 3.2 on 2021-04-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('link', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('image_link', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=70)),
                ('model', models.CharField(max_length=70)),
                ('year_of_issue', models.IntegerField()),
                ('socket', models.CharField(max_length=20)),
                ('cooling_system', models.NullBooleanField()),
                ('core', models.CharField(max_length=70)),
                ('number_of_cores', models.IntegerField()),
                ('number_of_threads', models.IntegerField()),
                ('base_frequency', models.IntegerField()),
                ('memory_type', models.CharField(max_length=4)),
                ('max_memory', models.CharField(max_length=8)),
                ('number_of_channels', models.IntegerField()),
                ('min_RAM_frequency_Mgc', models.IntegerField()),
                ('max_RAM_frequency_Mgc', models.IntegerField()),
                ('heat_dissipation_TDP_Wt', models.IntegerField()),
                ('integrated_graphics_core', models.NullBooleanField()),
                ('integrated_PCI_Express_controller', models.CharField(max_length=20)),
                ('support_64_bit_instruction_set', models.CharField(max_length=20)),
                ('multithreading', models.NullBooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
