# Generated by Django 3.2 on 2021-04-18 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20210418_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processor',
            name='base_frequency',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='cooling_system',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='core',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='heat_dissipation_TDP_Wt',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='integrated_PCI_Express_controller',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='integrated_graphics_core',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='max_RAM_frequency_Mgc',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='max_memory',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='memory_type',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='min_RAM_frequency_Mgc',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='model',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='multithreading',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='number_of_channels',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='number_of_cores',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='number_of_threads',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='price',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='socket',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='support_64_bit_instruction_set',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='year_of_issue',
        ),
    ]
