# Generated by Django 3.2 on 2021-04-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20210425_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='release_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='socket',
            field=models.CharField(max_length=50),
        ),
    ]
